language: cpp

compiler:
- clang
- gcc

env:
matrix:
- CONF=Debug   ARCH=x86_64
- CONF=Release ARCH=x86_64
- CONF=Debug   ARCH=x86
- CONF=Release ARCH=x86
global:
- ARCH_FLAGS_x86='-m32'         
- ARCH_FLAGS_x86_64='-msse4.2' 

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake valgrind
- if [ "$ARCH" = "x86" ]; then sudo apt-get install -qq g++-multilib libc6-dbg:i386; fi

install: true

before_script:
- mkdir build 
- eval "ARCH_FLAGS=\${ARCH_FLAGS_${ARCH}}" ; (cd build && cmake ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=$CONF -DCMAKE_CXX_FLAGS="$ARCH_FLAGS")

script:
- cd build
- make
- make tests
